---
  name: Deployment
  on:
    workflow_dispatch:
      inputs:
        env:
          description: "Deploy to (dev|prod|dev prod)"
          required: true
          default: "dev"
        clean:
          description: "Clean cache"
          required: true
          type: boolean
          default: false
        excludeSubfolder:
          description: "Exclude a subfolder from deletion"
          required: false
          default: ""
        index-mode:
          description: 'Type of indexing. "index" to push to Algolia, "console" for dry run.'
          required: true
          default: "index"
          type: choice
          options:
            - console
            - index
  env:
    NODE_OPTIONS: "--max-old-space-size=8192"
    TEMPLATE_ID_DEV: "1234"
    TEMPLATE_ID_PROD: "5678"

  jobs:
    deployment:
      name: Deployment
      uses: AdobeDocs/adp-devsite-workflow/.github/workflows/gatsby-deploy.yml@gatsby-workflow
      secrets: inherit
      with:
        env: ${{ inputs.env }}
        clean: ${{ inputs.clean }}
        excludeSubfolder: ${{ inputs.excludeSubfolder }}
        index-mode: ${{ inputs.index-mode }}
        NODE_OPTIONS: ${{ env.NODE_OPTIONS }}
        TEMPLATE_ID_DEV: ${{ env.TEMPLATE_ID_DEV }}
        TEMPLATE_ID_PROD: ${{ env.TEMPLATE_ID_PROD }}